### ISSUE TITLE
undefined method `new' for nil:NilClass when visiting certain link

### ISSUE THREAD

**Issue by gerryhd** [docmeta/rubydoc.info#125]
I'm not sure if this is the right place to report a bug in the website, but when I try to access this link
https://www.rubydoc.info/github/zenchild/Viewpoint/Viewpoint/EWS/Types/OutOfOffice

I get the following error

> undefined method `new' for nil:NilClass
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/helpers/html_helper.rb:126:in `html_markup_rdoc'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/helpers/html_helper.rb:59:in `htmlify'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/yard-sd-0.0.4/lib/yard-sd/sequence_diagram_mixin.rb:5:in `htmlify'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/templates/default/docstring/html/text.erb:3:in `_erb_cache_10'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:287:in `erb'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:365:in `render_section'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:259:in `block (2 levels) in run'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:256:in `each'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:256:in `block in run'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:394:in `add_options'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:255:in `run'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:277:in `block in yieldall'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:408:in `with_section'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:277:in `yieldall'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/templates/default/docstring/html/index.erb:5:in `_erb_cache_9'
> /home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-03515a8d25ad/lib/yard/templates/template.rb:287:in `erb'

And the trace goes on for a lot

**Comment by gerryhd** [comment]
seems fine now
