### ISSUE TITLE
Postgres errors when accessing some gem documentation

### ISSUE THREAD

**Issue by apainintheneck** [docmeta/rubydoc.info#193]
I was on rubygems.org and clicked over to rubydoc.info to see the documentation for a gem and ran into a Postgres error which caused the page not to load.

Gem: https://rubygems.org/gems/monad-oxide
Documentation: https://www.rubydoc.info/gems/monad-oxide/0.10.0

```
PG::ConnectionBad: could not translate host name "db" to address: Name does not resolve
```

<details>
<summary>Full Error</summary>

```
PG::ConnectionBad: could not translate host name "db" to address: Name does not resolve

/home/app/.gems/gems/pg-1.5.3/lib/pg/connection.rb:819:in `connect_start'
/home/app/.gems/gems/pg-1.5.3/lib/pg/connection.rb:819:in `connect_to_hosts'
/home/app/.gems/gems/pg-1.5.3/lib/pg/connection.rb:759:in `new'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/adapters/postgres.rb:231:in `connect'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/database/connecting.rb:248:in `new_connection'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/connection_pool.rb:161:in `make_new'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/database/connecting.rb:293:in `synchronize'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/adapters/postgres.rb:823:in `literal_string_append'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/dataset/sql.rb:60:in `literal_append'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/dataset/sql.rb:635:in `placeholder_literal_string_sql_append'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/sql.rb:112:in `to_s_append'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/dataset/sql.rb:1369:in `literal_expression_append'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/dataset/sql.rb:67:in `literal_append'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/dataset/placeholder_literalizer.rb:217:in `block in append_sql'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/dataset/placeholder_literalizer.rb:209:in `each'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/dataset/placeholder_literalizer.rb:209:in `append_sql'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/dataset/placeholder_literalizer.rb:203:in `sql'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/dataset/placeholder_literalizer.rb:190:in `first'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/dataset/actions.rb:255:in `first'
/home/app/.gems/gems/sequel-5.71.0/lib/sequel/model/plugins.rb:33:in `first'
/app/lib/gem_store.rb:23:in `[]'
/home/app/.gems/bundler/gems/yard-ab0e939b236b/lib/yard/server/router.rb:83:in `parse_library_from_path'
/home/app/.gems/bundler/gems/yard-ab0e939b236b/lib/yard/server/router.rb:112:in `route'
/home/app/.gems/bundler/gems/yard-ab0e939b236b/lib/yard/server/router.rb:56:in `call'
/home/app/.gems/bundler/gems/yard-ab0e939b236b/lib/yard/server/rack_adapter.rb:60:in `call'
/app/app.rb:414:in `block (2 levels) in <class:DocServer>'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1763:in `call'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1763:in `block in compile!'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1066:in `block (3 levels) in route!'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1084:in `route_eval'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1066:in `block (2 levels) in route!'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1115:in `block in process_route'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1113:in `catch'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1113:in `process_route'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1064:in `block in route!'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1061:in `each'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1061:in `route!'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1185:in `block in dispatch!'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `catch'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `invoke'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1180:in `dispatch!'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/sinatra.rb:23:in `dispatch!'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:996:in `block in call!'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `catch'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `invoke'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:996:in `call!'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:985:in `call'
/home/app/.gems/gems/rack-2.2.8/lib/rack/common_logger.rb:38:in `call'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:261:in `call'
/app/app.rb:192:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/app/app.rb:41:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/app/app.rb:30:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/rack-2.2.8/lib/rack/conditional_get.rb:27:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/rack-protection-3.1.0/lib/rack/protection/xss_header.rb:20:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/rack-protection-3.1.0/lib/rack/protection/path_traversal.rb:18:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/rack-protection-3.1.0/lib/rack/protection/json_csrf.rb:28:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/rack-protection-3.1.0/lib/rack/protection/base.rb:53:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/rack-protection-3.1.0/lib/rack/protection/base.rb:53:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/rack-protection-3.1.0/lib/rack/protection/frame_options.rb:33:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/rack-2.2.8/lib/rack/null_logger.rb:11:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:219:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/probes/middleware.rb:84:in `call'
/home/app/.gems/gems/skylight-5.3.4/lib/skylight/middleware.rb:99:in `call'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:2074:in `call'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1633:in `block in call'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1847:in `synchronize'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1847:in `synchronize'
/home/app/.gems/gems/sinatra-3.1.0/lib/sinatra/base.rb:1633:in `call'
/home/app/.gems/gems/puma-6.3.1/lib/puma/configuration.rb:270:in `call'
/home/app/.gems/gems/puma-6.3.1/lib/puma/request.rb:100:in `block in handle_request'
/home/app/.gems/gems/puma-6.3.1/lib/puma/thread_pool.rb:344:in `with_force_shutdown'
/home/app/.gems/gems/puma-6.3.1/lib/puma/request.rb:99:in `handle_request'
/home/app/.gems/gems/puma-6.3.1/lib/puma/server.rb:443:in `process_client'
/home/app/.gems/gems/puma-6.3.1/lib/puma/server.rb:245:in `block in run'
/home/app/.gems/gems/puma-6.3.1/lib/puma/thread_pool.rb:151:in `block in spawn_thread'
```

</details>

Interestingly enough going to https://www.rubydoc.info/gems/monad-oxide directly still sort of works though the error message is still visible. Clicking on any of the links causes the full error message to show again.

![Screen Shot 2024-10-05 at 3 57 17 PM](https://github.com/user-attachments/assets/b98d58bb-06ea-489d-90bc-b825dcad2bcc)

I have been able to replicate this with some other gems too though the error is not consistent between gems.

- Fear
  - Gem: https://rubygems.org/gems/fear
  - Documentation: https://www.rubydoc.info/gems/fear/3.0.0
- MicroJoin
  - Gem: https://rubygems.org/gems/microjoin
  - Documentation: https://www.rubydoc.info/gems/microjoin/0.1.0
- GPRC
  - Gem: https://rubygems.org/gems/grpc 
  - Documentation: https://www.rubydoc.info/gems/grpc/1.66.0

**Comment by lsegal** [comment]
Thanks for reporting, should be fixed now.

**Comment by apainintheneck** [comment]
It looks good now. Thanks fixing it!
