### ISSUE TITLE
Visiting missing method URL raises 500 error

### ISSUE THREAD

**Issue by bf4** [docmeta/rubydoc.info#70]
per https://github.com/mbleigh/acts-as-taggable-on/issues/419

Visiting http://rubydoc.info/github/mbleigh/acts-as-taggable-on/master/ActsAsTaggableOn/Taggable:taggable_on  returns a 500 error and

``` plain
undefined method `gsub' for nil:NilClass
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/server/doc_server_helper.rb:43:in `url_for_frameset'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/server/templates/default/layout/html/script_setup.erb:9:in `_erb_cache_2'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/template.rb:279:in `erb'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/templates/default/layout/html/headers.erb:13:in `_erb_cache_1'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/template.rb:279:in `erb'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/templates/default/layout/html/layout.erb:7:in `_erb_cache_0'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/template.rb:279:in `erb'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/template.rb:357:in `render_section'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/template.rb:251:in `block (2 levels) in run'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/template.rb:248:in `each'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/template.rb:248:in `block in run'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/template.rb:386:in `add_options'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/template.rb:247:in `run'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/template.rb:135:in `run'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/templates/engine.rb:88:in `render'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/code_objects/base.rb:480:in `format'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/server/commands/base.rb:141:in `render'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/server/commands/display_object_command.rb:23:in `run'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/server/commands/base.rb:95:in `call'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/server/commands/library_command.rb:65:in `call'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/server/router.rb:135:in `route_docs'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/server/router.rb:110:in `route'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/server/router.rb:54:in `call'
/home/deploy/.bundler/ruby/2.0.0/yard-b78dea29adaf/lib/yard/server/rack_adapter.rb:51:in `call'
/var/www/apps/rubydoc.info/releases/20100829162740/app.rb:337:in `block in <class:DocServer>'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1540:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1540:in `block in compile!'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `[]'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (3 levels) in route!'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:966:in `route_eval'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (2 levels) in route!'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:987:in `block in process_route'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `catch'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `process_route'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:948:in `block in route!'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `each'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `route!'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1059:in `block in dispatch!'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1056:in `dispatch!'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `block in call!'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `call!'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:870:in `call'
/var/www/apps/rubydoc.info/releases/20100829162740/app.rb:25:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/xss_header.rb:18:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/path_traversal.rb:16:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/json_csrf.rb:18:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/frame_options.rb:31:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/logger.rb:15:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:212:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:205:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:175:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1949:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1449:in `block in call'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1724:in `synchronize'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1724:in `synchronize'
/usr/local/lib/ruby/gems/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1449:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:552:in `process_client'
/usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:632:in `worker_loop'
/usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
/usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:142:in `start'
/usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.6.3/bin/unicorn:126:in `<top (required)>'
/usr/local/bin/unicorn:19:in `load'
/usr/local/bin/unicorn:19:in `<main>'
```

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.
